### ISSUE TITLE
Verify Email > Alert/Popup can't be dismissed

### ISSUE THREAD

**Issue by kaiansaari** [canyaio/CanSeek#79]
The verify email popup holds me hostage. This isn't cool.

![image](https://user-images.githubusercontent.com/26814804/43933150-657d2a36-9c8b-11e8-80c6-e0e4438e5d32.png)

**Comment by thetadotonline** [comment]
This is designed deliberately to guide user, once user verified their email, they are supposed to continue 
in a new tab, or refresh the old one.

Because firebase doesn't supply api to subscribe the `verify status`.

Maybe the design team can reword the wording to make it easier to accept.
@keelymalady Can you help me to do this?

**Comment by keelymalady** [comment]
Definitely @thetadotonline 

Plan A: Best solution for user
- add a link to return to canseek home page with the below copy
"Verification email sent"
"Check your inbox for an email from noreply@canseek.com"
"Return to CanSeek"

<img width="1435" alt="screen shot 2018-08-15 at 10 43 12 am" src="https://user-images.githubusercontent.com/39213616/44125834-1ae8b04e-a078-11e8-8886-3df2cc7f5c5d.png">
zpl.io/25qKm0r

Zeplin  zpl.io/25qKm0r


Plan B: No link alternative  
Update copy in pop up
"Verification email sent"
"Check your inbox for an email from noreply@canseek.com"
"Refresh browser to return to CanSeek"
